spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  aop:
    auto: true
    proxy-target-class: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  profiles:
    active: container

#  devtools:
#    restart:
#      additional-paths: .


---
spring:
  profiles: container
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=lfc;useUnicode=true;characterEncoding=UTF-8
    username: sa
    password: Leftjs@github.com
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: com.leftjs.lfc.SQLServerUnicodeDialect
    database: SQL_SERVER
    generate-ddl: true
#    openInView: false
#    generate-ddl: false
